name: Build extension

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'extern/**'
      - 'sourcemod/scripting/include/**'
      - 'src/**'
      - 'AMBuilder'
      - 'AMBuildScript'
      - 'PackageScript'
      - 'configure.py'
  push:
    paths:
      - 'extern/**'
      - 'sourcemod/scripting/include/**'
      - 'src/**'
      - 'AMBuilder'
      - 'AMBuildScript'
      - 'PackageScript'
      - 'configure.py'
  workflow_call:
    inputs:
      source_ref:
        required: false
        type: string

env:
  PYTHONUTF8: "1"
  PYTHON_VERSION: "3.13"

jobs:
  Build:
    name: Build with ${{ matrix.os_short }} ${{ matrix.sm_version }} ${{ matrix.target_arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        # https://github.com/actions/runner-images#available-images
        os: [ubuntu-latest, ubuntu-22.04, windows-latest, windows-2022]
        sm_version: [sm_latest, sm_1_12]
        target_arch: [x86, x64]
        include:
          - os: ubuntu-latest
            os_short: ubuntu_latest
          - os: ubuntu-22.04
            os_short: ubuntu_22_04
          - os: windows-latest
            os_short: win_latest
          - os: windows-2022
            os_short: win_2022
          - sm_version: sm_latest
            sm_ref: master
          - sm_version: sm_1_12
            sm_ref: 1.12-dev
          - target_arch: x86
            vs_dev_arch: x86
          - target_arch: x64
            vs_dev_arch: x86_64

    steps:
      - name: Install (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y gcc g++ g++-multilib libstdc++6
          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=g++" >> $GITHUB_ENV

      - name: Install (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          :: See https://github.com/microsoft/vswhere/wiki/Find-VC
          for /f "usebackq delims=*" %%i in (`vswhere -latest -property installationPath`) do (
            call "%%i"\Common7\Tools\vsdevcmd.bat -arch=${{ matrix.vs_dev_arch }} -host_arch=x64
          )

          :: Loop over all environment variables and make them global.
          for /f "delims== tokens=1,2" %%a in ('set') do (
            echo>>"%GITHUB_ENV%" %%a=%%b
          )

      - name: Add msbuild to PATH (Windows)
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v2

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install AMBuild
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip install git+https://github.com/alliedmodders/ambuild

      - name: Check out SourceMod
        uses: actions/checkout@v6
        with:
          repository: alliedmodders/sourcemod
          submodules: recursive
          path: sourcemod
          ref: ${{ matrix.sm_ref }}

      - name: Check out Log4sp
        uses: actions/checkout@v6
        with:
          path: log4sp
          ref: ${{ inputs.source_ref || github.ref }}

      - name: Build extension
        id: build
        shell: bash
        working-directory: log4sp
        run: |
          mkdir -p build && cd build
          python3 ../configure.py --enable-optimize --sm-path="${{ github.workspace }}/sourcemod" --targets ${{ matrix.target_arch }}
          ambuild

          version=$(grep -E 'SMEXT_CONF_VERSION' "../src/smsdk_config.h" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          echo "version=${version}" >> "$GITHUB_OUTPUT"

          short_hash="${GITHUB_SHA::7}"
          echo "short_hash=${short_hash}" >> "$GITHUB_OUTPUT"

      - name: Uploading packages
        uses: actions/upload-artifact@v7
        with:
          name: sm-ext-log4sp-v${{ steps.build.outputs.version }}.${{ steps.build.outputs.short_hash }}-${{ matrix.os_short }}-${{ matrix.sm_version }}-${{ matrix.target_arch }}
          path: log4sp/build/package
          if-no-files-found: error
